name: Enviar e-mail com Gmail

on:
  workflow_dispatch:
    inputs:
      destinatario:
        description: 'E-mail do destinatário'
        required: true
        default: 'paludetolucas@gmail.com'

jobs:
  enviar_email:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar e-mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: false
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "🚀 Notificação do GitHub Actions"
          to: ${{ github.event.inputs.destinatario }}
          from: GitHub Actions <${{ secrets.GMAIL_USERNAME }}>
          html_body: |
            <h2>✅ Build finalizado com sucesso!</h2>
            <p>Este e-mail foi enviado automaticamente pelo GitHub Actions.</p>
