# CI de Nível 02 - Disparo agendado

# nome do nosso 'pipeline'
name: 'Execução Agendada'

# regras de disparo (gatilhos/triggers)
# gatilho de exec agendada = schedule

on:
  schedule:
    - cron: '0 6 * * 1'

# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:

    #maquina que o job vai executar
    runs-on: ubuntu-latest

    # passos do script de build
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalacao do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      #instalacao do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn 
      
      # instalacao das dependências
      - name: Instalando dependências
        run: yarn

      # instalacao do Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      # executar os testes e2e
      - name: Executando Testes e2e
        run: yarn run e2e

      - name: Enviar e-mail de sucesso
        if: success()   # executa só se os passos anteriores tiveram sucesso
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: false
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "✅ Testes E2E passaram com sucesso!"
          to: seu-email@exemplo.com
          from: GitHub Actions <${{ secrets.GMAIL_USERNAME }}>
          html_body: |
            <h2>Os testes automatizados foram concluídos com sucesso!</h2>
            <p>Este e-mail foi enviado automaticamente pelo GitHub Actions.</p>
